config/routes.rb
if RUBY_VERSION.to_f >= 1.9
  require 'sidekiq/web'
end

Goldencobra::Engine.routes.draw do
  get 'switch_language/:locale'        => 'articles#switch_language', as: :switch_language
  get 'frontend_logout/:usermodel'     => 'sessions#logout', as: :frontend_logout
  get 'manage/render_admin_menue'      => 'manage#render_admin_menue'
  get 'call_for_support'               => 'manage#call_for_support'
  post 'frontend_login/:usermodel'     => 'sessions#login', as: :frontend_login
  post 'frontend_register/:usermodel'  => 'sessions#register', as: :frontend_register
  post 'manage/article_visibility/:id' => 'manage#article_visibility'

  if RUBY_VERSION.to_f >= 1.9
    mount Sidekiq::Web => '/admin/background'
  end

  # post '/api/v1/tokens' => 'goldencobra/api/v1/tokens_controller#create'
  namespace 'api' do
    namespace 'v1' do
      resources :tokens, only: [:create]
    end

    namespace 'v2' do
      get '/articles'                 => 'articles#index'
      get '/articles/search'          => 'articles#search'
      get '/articles/breadcrumb/*url' => 'articles#breadcrumb'
      get '/articles/*url'            => 'articles#show'
      get '/locale_string'            => 'locales#get_string'
      get '/setting_string'           => 'settings#get_string'
      get '/uploads'                  => 'uploads#index'
      post '/articles/create'         => 'articles#create'
      post '/articles/update'         => 'articles#update'
      get '/navigation_menus'         => 'navigation_menus#index'
      get '/navigation_menus/active'  => 'navigation_menus#active_ids'
    end
  end

  get 'sitemap', to: 'articles#sitemap', defaults: { format: 'xml' }

  devise_for :visitors, controllers: { omniauth_callbacks: 'visitors/omniauth_callbacks' }
  devise_scope :visitors do
    get '/visitors/auth/:provider' => 'omniauth_callbacks#passthru'
  end

  #match '/*article_id.pdf', to: 'articles#convert_to_pdf'
  get '/*article_id', to: 'articles#show'

  root to: 'articles#show', defaults: { startpage: true }
end

app/views/goldencobra/admin/shared/_help.html.erb
<% exclude_list = ["tablerow", "assign", "break", "capture", "case", "comment", "continue", "cycle", "decrement", "for", "if", "ifchanged", "include", "increment", "raw", "unless"] %>
<p>Folgende Funktionen können sie in Textfeldern verwenden um zusätzlichen Inhalt darzustellen</p>
<ul>
	<% if false #defined?(Liquid::Template) == "constant" && defined?(Liquid::Template.tags) == "method" %>
		<% Liquid::Template.tags.each do |key,value| %>
			<% next if exclude_list.include?(key) %>
			<li><b><%= key %></b><br/>
				<% if value.respond_to?(:description) %>
					<%= value.description %><br/>
				<% end %>
				<% if value.respond_to?(:usage) %>
					Verwendung:<br/><%= value.usage  %>
				<% end %>
			</li>
		<% end %>
	<% end %>
</ul>

app/views/goldencobra/admin/shared/_item.html.erb
<li id="overview_item_<%= item.id %>" class="listItem">
	<div class="item">
		<% if item.children.count > 0 %>
			<div class="folder"></div>
		<% else %>
			<div class="last_folder"></div>
		<% end %>

		<% if Goldencobra::Permission.restricted?(item) %>
			<div class="secured"></div>
		<% end %>
		<div class="title"><%= link_to item.send(link_name), eval("admin_#{url_path.pluralize}_path(:q => {:parent_ids_in => item.id})"), :title => "Pfad anzeigen" %></div>
		<div class="options">
			<%= link_to I18n.t('active_admin.shared.views.item.link1'), eval("edit_admin_#{url_path}_path(item)"), :class => "edit_link", :title => I18n.t('active_admin.shared.views.item.title1') %>
			<%= link_to I18n.t('active_admin.shared.views.item.link2'), eval("new_admin_#{url_path}_path(:parent => item)"), :class => "new_link", :title => I18n.t('active_admin.shared.views.item.title2') %>
		</div>
	</div>
	<% if item.children %>
		<ul style="display: none;">
			<% item.children.order(order_by.to_sym).each do |art|%>
				<%= render :partial => "/goldencobra/admin/shared/item", :object => art, :locals => {:link_name => link_name, :url_path => url_path, :order_by => order_by } %>
			<% end %>
		</ul>
	<% end %>
</li>

app/views/goldencobra/admin/shared/_next_item.html.erb
<% table_name = resource.class.table_name %>
<% resource_to_edit = resource.class.where("#{table_name}.id > ?", resource.id).order("#{table_name}.id ASC").first %>
<% if resource_to_edit %>
  <%= link_to "#{active_admin_config.resource_label} ->", edit_resource_path(resource_to_edit) %>
<% end %>

app/views/goldencobra/admin/shared/_overview.html.erb
<% order_by ||= "id" %>
<% overview.order(order_by.to_sym).each do |root| %>
  <script src="/admin/articles/load_overviewtree?order_by=<%= order_by %>&url_path=<%= url_path %>&link_name=<%= link_name %>&object_id=<%= root.id %>&object_class=<%= root.class.to_s %>" type="text/javascript" charset="utf-8" async defer></script>
<% end %>
<div class="overview-sidebar">
  <ul id="overview-sidebar_list">
    <% overview.order(order_by.to_sym).each do |root| %>
      <li id="temp_list_item_<%= root.id %>" class="listItem">
        <div class="item">
          <div class="last_folder"></div>
          <div class="title">
            loading <%= root.send(link_name) %> ...
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/goldencobra/admin/shared/_prev_item.html.erb
<% table_name = resource.class.table_name %>
<% resource_to_edit = resource.class.where("#{table_name}.id < ?", resource.id).order("#{table_name}.id DESC").first %>
<% if resource_to_edit %>
  <%= link_to "<- #{active_admin_config.resource_label}", edit_resource_path(resource_to_edit) %>
<% end %>

app/views/goldencobra/admin/shared/_react_overview.html.erb
<div id="overviewTree"></div>

<% 
  url ||= "/admin/articles/load_overviewtree_as_json"
  class_name ||= 'articles'
%>

<script type="text/javascript">
  React.render(
      React.createElement(ListOfArticlesBox, { url: '<%= url %>', class_name: '<%= class_name %>' }),
      document.getElementById('overviewTree')
  );
</script>

app/views/goldencobra/admin/shared/load_overviewtree.js.erb
<% object_to_render = object_class.constantize.find_by_id(object_id) %>
var htmlString = "<%= escape_javascript( render :partial => '/goldencobra/admin/shared/item',
                                                                  :object => object_to_render,
                                                                  :locals => {:link_name => link_name, :url_path => url_path, :order_by => order_by }
                                                          ) %>"
var sidebarList = document.getElementById('overview-sidebar_list');
var presentHTML = sidebarList.innerHTML;

sidebarList.innerHTML = presentHTML + htmlString;
var d_nested = document.getElementById('temp_list_item_<%= object_id %>');
var throwawayNode = sidebarList.removeChild(d_nested);